Website
HOMS-OSS/perf-rust pull request #92
Opened 2021-08-11 20:39 UTC by Sl1mb0

- Adds an image of Ruperf the Crab
 - Outlines 3 things our tool aims to achieve
 - Provides brief descriptions of other tools and how our tool hopes to add the existing landscape
 - Adds brief outlines of other sections that I will fill out later today.

2021-08-11 21:06 UTC, Boursler approved these changes
Hilarious read, thank you for doing this.

2021-08-11 22:06 UTC, kagutaba256 commented
He lives... 👀👀 Excellent work, these sections all seem good to include.

2021-08-11 22:23 UTC, kagutaba256 approved these changes

2021-08-12 16:36 UTC, ScherrerMichael commented on index.html
> +`ruperf` was borne out of a desire to achieve three things:
Was wondering if `"born"` was intentional or not.

2021-08-12 16:41 UTC, ScherrerMichael requested changes
Made a note about a single words spelling inline. First time doing an inline suggestion, I hope it shows up in this review. :)

Edit: Ah it separates the comments, cool! Looks great!

2021-08-13 04:17 UTC, ScherrerMichael approved these changes

2021-08-14 00:31 UTC, merged